[package]
name = "rockscache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
r2d2 = "0.8"
rand = "0.8"
redis = {version="0.23", features=["r2d2"]}
# tokio = {version = "1", default-features = false, features = ["rt"]}
uuid = { version = "1", features=["v4"] }

singleflight = {path="singleflight"}
