name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version:
          - latest
        rust:
          - stable
    steps:
      - uses: actions/checkout@v3
      - name: Start Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - run: cargo build --verbose
      - run: cargo test --verbose
